import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import fs from 'fs';
import path from 'path';
import { format, eachDayOfInterval, parseISO } from 'date-fns';

export interface RosterPdfEntry {
  date: string;
  userId: string;
  userName: string;
  shiftName: string;
}

export interface ShiftTemplateInfo {
  id: string;
  name: string;
  durationHours: number;
}

export interface GenerateRosterPdfParams {
  departmentName: string;
  hospitalName: string;
  startDate: string; // ISO date string e.g. "2026-07-27"
  endDate: string;   // ISO date string
  inchargeName: string;
  entries: RosterPdfEntry[];
  shiftTemplates: ShiftTemplateInfo[];
}

const BRAND_BLUE = '#1e5cd4';
const BRAND_GOLD = '#fad23b';
const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export function generateRosterPdf(params: GenerateRosterPdfParams): Buffer {
  const { departmentName, hospitalName, startDate, endDate, inchargeName, entries, shiftTemplates } = params;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Logo ---
  let logoBase64: string | null = null;
  try {
    const logoPath = path.join(process.cwd(), 'public', 'logo.png');
    const logoData = fs.readFileSync(logoPath);
    logoBase64 = `data:image/png;base64,${logoData.toString('base64')}`;
  } catch {
    // Logo not found — skip
  }

  if (logoBase64) {
    doc.addImage(logoBase64, 'PNG', pageWidth / 2 - 12, 8, 24, 10);
  }

  // --- Title ---
  doc.setFontSize(18);
  doc.setTextColor(BRAND_BLUE);
  doc.setFont('helvetica', 'bold');
  doc.text('Duty Roster', pageWidth / 2, 24, { align: 'center' });

  // --- Meta line ---
  const start = parseISO(startDate);
  const end = parseISO(endDate);
  const monthYear = format(start, 'MMMM yyyy');
  const metaLine = `${hospitalName} | ${departmentName} | ${monthYear}`;
  doc.setFontSize(10);
  doc.setTextColor('#333333');
  doc.setFont('helvetica', 'normal');
  doc.text(metaLine, pageWidth / 2, 32, { align: 'center' });

  // --- Incharge line ---
  const inchargeLine = inchargeName ? `Assigned By: ${inchargeName}` : '';
  if (inchargeLine) {
    doc.setFontSize(9);
    doc.setTextColor('#555555');
    doc.text(inchargeLine, pageWidth / 2, 38, { align: 'center' });
  }

  // --- Build table data ---
  const days = eachDayOfInterval({ start, end });
  const shiftNames = shiftTemplates.map((t) => t.name);

  // Transform entries into a map: dateStr -> shiftName -> userNames[]
  const rosterMap: Record<string, Record<string, string[]>> = {};
  for (const entry of entries) {
    const dateKey = entry.date.substring(0, 10); // "YYYY-MM-DD"
    if (!rosterMap[dateKey]) rosterMap[dateKey] = {};
    if (!rosterMap[dateKey][entry.shiftName]) rosterMap[dateKey][entry.shiftName] = [];
    rosterMap[dateKey][entry.shiftName].push(entry.userName);
  }

  // Build body rows: [Date, Shift1, Shift2, ...]
  const body: string[][] = days.map((day) => {
    const dateKey = format(day, 'yyyy-MM-dd');
    const dayLabel = `${DAY_NAMES[day.getDay()]} ${format(day, 'MMM dd')}`;
    const row: string[] = [dayLabel];
    for (const shiftName of shiftNames) {
      const doctors = (rosterMap[dateKey] && rosterMap[dateKey][shiftName]) || [];
      row.push(doctors.length > 0 ? doctors.join(', ') : '—');
    }
    return row;
  });

  // Headers: [Date, Shift1, Shift2, ...]
  const headers = ['Date', ...shiftNames.map((s) => `${s}`)];

  // --- Render table ---
  autoTable(doc, {
    startY: 44,
    head: [headers],
    body,
    theme: 'grid',
    styles: {
      fontSize: 8,
      cellPadding: 2,
      lineColor: [200, 200, 200],
      lineWidth: 0.3,
    },
    headStyles: {
      fillColor: hexToRgb(BRAND_BLUE),
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      valign: 'middle',
      halign: 'center',
    },
    alternateRowStyles: {
      fillColor: [245, 248, 255],
    },
    columnStyles: {
      0: { halign: 'left', fontStyle: 'bold', cellWidth: 40 },
    },
  });

  // --- Footer ---
  const finalY = (doc as any).lastAutoTable?.finalY ?? pageHeight - 15;
  doc.setFontSize(7);
  doc.setTextColor('#999999');
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by RosterDoc \u2014 HealthcareHustlers', pageWidth / 2, Math.min(finalY + 10, pageHeight - 8), {
    align: 'center',
  });

  // --- Return as Buffer ---
  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}

function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return [30, 92, 212];
  return [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)];
}
